using Domain.Entities;
using Infrastructure.Contracts;
using Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

/*
 * Created by   : Bella
 * Date created : 29.03.2023
 * Modified by  : 
 * Last modified: 
 * Reviewed by  :
 * Date reviewed:
 */
namespace Infrastructure.Repositories
{
    public class ARTRegisterRepository : Repository<ARTService>, IARTRegisterRepository
    {
        private readonly DataContext context;

        public ARTRegisterRepository(DataContext context) : base(context)
        {
            this.context = context;
        }

        public async Task<ARTService> GetARTRegisterByKey(Guid key)
        {
            try
            {
                ARTService aRTService = await context.ARTServices.AsNoTracking().FirstOrDefaultAsync(b => b.Oid == key && b.IsDeleted == false);

                if (aRTService is not null)
                {
                    aRTService.EncounterDate = await context.Encounters.Where(x => x.Oid == aRTService.EncounterId).Select(x => x.OPDVisitDate ?? x.IPDAdmissionDate ?? x.DateCreated).FirstOrDefaultAsync();
                    aRTService.ClinicianName = await context.UserAccounts.Where(x => x.Oid == aRTService.CreatedBy).Select(x => x.FirstName + " " + x.Surname).FirstOrDefaultAsync() ?? "";
                    aRTService.FacilityName = await context.Facilities.Where(x => x.Oid == aRTService.CreatedIn).Select(x => x.Description).FirstOrDefaultAsync() ?? "";
                }

                return aRTService;
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IEnumerable<ARTService>> GetARTRegisters()
        {
            try
            {
                return await context.ARTServices.AsNoTracking()
                    .Join(
                        context.Encounters.AsNoTracking(),
                        artService => artService.EncounterId,
                        encounter => encounter.Oid,
                        (artService, encounter) => new ARTService
                        {
                            Oid = artService.Oid,
                            ARTNumber = artService.ARTNumber,
                            IsARTNumberAutoGenerated = artService.IsARTNumberAutoGenerated,
                            DisclosureCounselling = artService.DisclosureCounselling,
                            CoupleCounselling = artService.CoupleCounselling,
                            NotificationServices = artService.NotificationServices,
                            InterpersonalViolenceScreened = artService.InterpersonalViolenceScreened,
                            IsITPNSOffered = artService.IsITPNSOffered,
                            IsITPNSAccepted = artService.IsITPNSAccepted,
                            NumberOfBiologicalContacts = artService.NumberOfBiologicalContacts,
                            NumberOfSexualContacts = artService.NumberOfSexualContacts,
                            NumberOfOtherContacts = artService.NumberOfOtherContacts,
                            ConsentForFollowUpPrograms = artService.ConsentForFollowUpPrograms,
                            CanReceiveCalls = artService.CanReceiveCalls,
                            CanReceiveSMS = artService.CanReceiveSMS,
                            CanPatientBeVisitedAtHome = artService.CanPatientBeVisitedAtHome,
                            CanPatientBeVisitedAtWork = artService.CanPatientBeVisitedAtWork,
                            IsEnrolledInSupportGroup = artService.IsEnrolledInSupportGroup,
                            DoesClientWantToBeEnrolledInSupportGroup = artService.DoesClientWantToBeEnrolledInSupportGroup,
                            DoesChildKnowStatus = artService.DoesChildKnowStatus,
                            ARTTempNumber = artService.ARTTempNumber,
                            EncounterDate = encounter.OPDVisitDate ?? encounter.IPDAdmissionDate ?? encounter.DateCreated,
                            CreatedBy = artService.CreatedBy,
                            CreatedIn = artService.CreatedIn,
                            DateModified = artService.DateModified,
                            DateCreated = artService.DateCreated,
                            EncounterId = artService.EncounterId,
                            EncounterType = artService.EncounterType,
                            IsDeleted = artService.IsDeleted,
                            IsSynced = artService.IsSynced,
                            ModifiedBy = artService.ModifiedBy,
                            ModifiedIn = artService.ModifiedIn,
                            ClinicianName = context.UserAccounts.Where(x => x.Oid == artService.CreatedBy).Select(x => x.FirstName + " " + x.Surname).FirstOrDefault() ?? "",
                            FacilityName = context.Facilities.Where(x => x.Oid == artService.CreatedIn).Select(x => x.Description).FirstOrDefault() ?? "",

                            // Add other properties as needed
                        })
                    .Where(artService => artService.IsDeleted == false)
                    .OrderByDescending(x => x.EncounterDate)
                    .ToListAsync();
            }
            catch (Exception)
            {
                throw;
            }
        }

        /// <summary>
        /// The method is used to get a family member by clientId.
        /// </summary>
        /// <param name="clientId"></param>
        /// <returns>Returns a family member if the clientId is matched.</returns>

        public async Task<IEnumerable<ARTService>> GetARTRegisterbyClienId(Guid clientId)
        {
            try
            {
                return await context.ARTServices.Where(artService => artService.IsDeleted == false && artService.Oid == clientId).AsNoTracking()
                    .Join(
                        context.Encounters.AsNoTracking(),
                        artService => artService.EncounterId,
                        encounter => encounter.Oid,
                        (artService, encounter) => new ARTService
                        {
                            Oid = artService.Oid,
                            ARTNumber = artService.ARTNumber,
                            IsARTNumberAutoGenerated = artService.IsARTNumberAutoGenerated,
                            DisclosureCounselling = artService.DisclosureCounselling,
                            CoupleCounselling = artService.CoupleCounselling,
                            NotificationServices = artService.NotificationServices,
                            InterpersonalViolenceScreened = artService.InterpersonalViolenceScreened,
                            IsITPNSOffered = artService.IsITPNSOffered,
                            IsITPNSAccepted = artService.IsITPNSAccepted,
                            NumberOfBiologicalContacts = artService.NumberOfBiologicalContacts,
                            NumberOfSexualContacts = artService.NumberOfSexualContacts,
                            NumberOfOtherContacts = artService.NumberOfOtherContacts,
                            ConsentForFollowUpPrograms = artService.ConsentForFollowUpPrograms,
                            CanReceiveCalls = artService.CanReceiveCalls,
                            CanReceiveSMS = artService.CanReceiveSMS,
                            CanPatientBeVisitedAtHome = artService.CanPatientBeVisitedAtHome,
                            CanPatientBeVisitedAtWork = artService.CanPatientBeVisitedAtWork,
                            IsEnrolledInSupportGroup = artService.IsEnrolledInSupportGroup,
                            DoesClientWantToBeEnrolledInSupportGroup = artService.DoesClientWantToBeEnrolledInSupportGroup,
                            DoesChildKnowStatus = artService.DoesChildKnowStatus,
                            ARTTempNumber = artService.ARTTempNumber,
                            EncounterDate = encounter.OPDVisitDate ?? encounter.IPDAdmissionDate ?? encounter.DateCreated,
                            CreatedBy = artService.CreatedBy,
                            CreatedIn = artService.CreatedIn,
                            DateModified = artService.DateModified,
                            DateCreated = artService.DateCreated,
                            EncounterId = artService.EncounterId,
                            EncounterType = artService.EncounterType,
                            IsDeleted = artService.IsDeleted,
                            IsSynced = artService.IsSynced,
                            ModifiedBy = artService.ModifiedBy,
                            ModifiedIn = artService.ModifiedIn,
                            ClinicianName = context.UserAccounts.Where(x => x.Oid == artService.CreatedBy).Select(x => x.FirstName + " " + x.Surname).FirstOrDefault() ?? "",
                            FacilityName = context.Facilities.Where(x => x.Oid == artService.CreatedIn).Select(x => x.Description).FirstOrDefault() ?? "",

                            // Add other properties as needed
                        }).OrderByDescending(x => x.EncounterDate).ToListAsync();

                //return await QueryAsync(b => b.IsDeleted == false && b.Oid == clientId);
            }
            catch (Exception)
            {
                throw;
            }
        }
        public async Task<IEnumerable<ARTService>> GetARTRegisterbyClienIdLast24Hours(Guid clientId)
        {
            try
            {
                return await context.ARTServices.Where(artService => artService.IsDeleted == false && artService.Oid == clientId).AsNoTracking()
                    .Join(
                        context.Encounters.AsNoTracking(),
                        artService => artService.EncounterId,
                        encounter => encounter.Oid,
                        (artService, encounter) => new ARTService
                        {
                            Oid = artService.Oid,
                            ARTNumber = artService.ARTNumber,
                            IsARTNumberAutoGenerated = artService.IsARTNumberAutoGenerated,
                            DisclosureCounselling = artService.DisclosureCounselling,
                            CoupleCounselling = artService.CoupleCounselling,
                            NotificationServices = artService.NotificationServices,
                            InterpersonalViolenceScreened = artService.InterpersonalViolenceScreened,
                            IsITPNSOffered = artService.IsITPNSOffered,
                            IsITPNSAccepted = artService.IsITPNSAccepted,
                            NumberOfBiologicalContacts = artService.NumberOfBiologicalContacts,
                            NumberOfSexualContacts = artService.NumberOfSexualContacts,
                            NumberOfOtherContacts = artService.NumberOfOtherContacts,
                            ConsentForFollowUpPrograms = artService.ConsentForFollowUpPrograms,
                            CanReceiveCalls = artService.CanReceiveCalls,
                            CanReceiveSMS = artService.CanReceiveSMS,
                            CanPatientBeVisitedAtHome = artService.CanPatientBeVisitedAtHome,
                            CanPatientBeVisitedAtWork = artService.CanPatientBeVisitedAtWork,
                            IsEnrolledInSupportGroup = artService.IsEnrolledInSupportGroup,
                            DoesClientWantToBeEnrolledInSupportGroup = artService.DoesClientWantToBeEnrolledInSupportGroup,
                            DoesChildKnowStatus = artService.DoesChildKnowStatus,
                            ARTTempNumber = artService.ARTTempNumber,
                            EncounterDate = encounter.OPDVisitDate ?? encounter.IPDAdmissionDate ?? encounter.DateCreated,
                            CreatedBy = artService.CreatedBy,
                            CreatedIn = artService.CreatedIn,
                            DateModified = artService.DateModified,
                            DateCreated = artService.DateCreated,
                            EncounterId = artService.EncounterId,
                            EncounterType = artService.EncounterType,
                            IsDeleted = artService.IsDeleted,
                            IsSynced = artService.IsSynced,
                            ModifiedBy = artService.ModifiedBy,
                            ModifiedIn = artService.ModifiedIn,
                            ClinicianName = context.UserAccounts.Where(x => x.Oid == artService.CreatedBy).Select(x => x.FirstName + " " + x.Surname).FirstOrDefault() ?? "",
                            FacilityName = context.Facilities.Where(x => x.Oid == artService.CreatedIn).Select(x => x.Description).FirstOrDefault() ?? "",

                            // Add other properties as needed
                        }).OrderByDescending(x => x.EncounterDate).ToListAsync();

                //return await QueryAsync(b => b.IsDeleted == false && b.Oid == clientId);
            }
            catch (Exception)
            {
                throw;
            }
        }

        /// <summary>
        /// The method is used to Get ARTService by EncounterID.
        /// </summary>
        /// <param name="encounterID"></param>
        /// <returns>Returns a ARTServices by EncounterID.</returns>
        public async Task<IEnumerable<ARTService>> GetARTRegisterByEncounterID(Guid encounterID)
        {
            try
            {
                return await context.ARTServices.AsNoTracking().Where(artService => artService.IsDeleted == false && artService.EncounterId == encounterID)
                     .Join(
                         context.Encounters.AsNoTracking(),
                         artService => artService.EncounterId,
                         encounter => encounter.Oid,
                         (artService, encounter) => new ARTService
                         {
                             Oid = artService.Oid,
                             ARTNumber = artService.ARTNumber,
                             IsARTNumberAutoGenerated = artService.IsARTNumberAutoGenerated,
                             DisclosureCounselling = artService.DisclosureCounselling,
                             CoupleCounselling = artService.CoupleCounselling,
                             NotificationServices = artService.NotificationServices,
                             InterpersonalViolenceScreened = artService.InterpersonalViolenceScreened,
                             IsITPNSOffered = artService.IsITPNSOffered,
                             IsITPNSAccepted = artService.IsITPNSAccepted,
                             NumberOfBiologicalContacts = artService.NumberOfBiologicalContacts,
                             NumberOfSexualContacts = artService.NumberOfSexualContacts,
                             NumberOfOtherContacts = artService.NumberOfOtherContacts,
                             ConsentForFollowUpPrograms = artService.ConsentForFollowUpPrograms,
                             CanReceiveCalls = artService.CanReceiveCalls,
                             CanReceiveSMS = artService.CanReceiveSMS,
                             CanPatientBeVisitedAtHome = artService.CanPatientBeVisitedAtHome,
                             CanPatientBeVisitedAtWork = artService.CanPatientBeVisitedAtWork,
                             IsEnrolledInSupportGroup = artService.IsEnrolledInSupportGroup,
                             DoesClientWantToBeEnrolledInSupportGroup = artService.DoesClientWantToBeEnrolledInSupportGroup,
                             DoesChildKnowStatus = artService.DoesChildKnowStatus,
                             ARTTempNumber = artService.ARTTempNumber,
                             EncounterDate = encounter.OPDVisitDate ?? encounter.IPDAdmissionDate ?? encounter.DateCreated,
                             CreatedBy = artService.CreatedBy,
                             CreatedIn = artService.CreatedIn,
                             DateModified = artService.DateModified,
                             DateCreated = artService.DateCreated,
                             EncounterId = artService.EncounterId,
                             EncounterType = artService.EncounterType,
                             IsDeleted = artService.IsDeleted,
                             IsSynced = artService.IsSynced,
                             ModifiedBy = artService.ModifiedBy,
                             ModifiedIn = artService.ModifiedIn,
                             ClinicianName = context.UserAccounts.Where(x => x.Oid == artService.CreatedBy).Select(x => x.FirstName + " " + x.Surname).FirstOrDefault() ?? "",
                             FacilityName = context.Facilities.Where(x => x.Oid == artService.CreatedIn).Select(x => x.Description).FirstOrDefault() ?? "",

                             // Add other properties as needed
                         })

                     .OrderByDescending(x => x.EncounterDate)
                     .ToListAsync();
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}