using Domain.Entities;
using Microsoft.EntityFrameworkCore;

/*
 * Created by    : Lion
 * Date created  : 25.03.2023
 * Modified by   :
 * Last modified : 
 * Reviewed by   : 
 * Date Reviewed : 
 */
namespace Infrastructure
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options) : base(options)
        {

        }
        #region Lookup Entities
        public DbSet<Country> Countries { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Town> Towns { get; set; }
        public DbSet<HomeLanguage> HomeLanguages { get; set; }
        public DbSet<Occupation> Occupations { get; set; }
        public DbSet<EducationLevel> EducationLevels { get; set; }
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<HIVTestingReason> HIVTestingReasons { get; set; }
        public DbSet<HIVNotTestingReason> HIVNotTestingReasons { get; set; }
        public DbSet<HIVRiskFactor> HIVRiskFactors { get; set; }
        public DbSet<ServicePoint> ServicePoints { get; set; }
        public DbSet<VisitType> VisitTypes { get; set; }
        public DbSet<ClientType> ClientTypes { get; set; }
        public DbSet<AnatomicAxis> AnatomicAxes { get; set; }
        public DbSet<PathologyAxis> PathologyAxes { get; set; }
        public DbSet<ICPC2Description> ICPC2Descriptions { get; set; }
        public DbSet<ICDDiagnosis> ICDDiagnoses { get; set; }
        public DbSet<DeathRecord> DeathRecords { get; set; }
        public DbSet<CovidSymptom> CovidSymptoms { get; set; }
        public DbSet<VaccineType> VaccineTypes { get; set; }
        public DbSet<Vaccine> Vaccines { get; set; }
        public DbSet<VaccineDose> VaccineDoses { get; set; }
        public DbSet<ConstitutionalSymptom> ConstitutionalSymptoms { get; set; }
        public DbSet<ConstitutionalSymptomType> ConstitutionalSymptomTypes { get; set; }
        public DbSet<TBSymptom> TBSymptoms { get; set; }
        public DbSet<PhysicalSystem> PhysicalSystems { get; set; }
        public DbSet<NTGLevelOneDiagnosis> NTGLevelOneDianoses { get; set; }
        public DbSet<NTGLevelTwoDiagnosis> NTGLevelTwoDiagnoses { get; set; }
        public DbSet<NTGLevelThreeDiagnosis> NTGLevelThreeDiagnoses { get; set; }
        public DbSet<Allergy> Allergies { get; set; }
        public DbSet<AllergicDrug> AllergicDrugs { get; set; }
        public DbSet<Contraceptive> Contraceptives { get; set; }
        public DbSet<CaCxScreeningMethod> CaCxScreeningMethods { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Firm> Firms { get; set; }
        public DbSet<Ward> Wards { get; set; }
        public DbSet<Bed> Beds { get; set; }
        public DbSet<ExposureType> ExposureTypes { get; set; }
        public DbSet<Risks> Risks { get; set; }
        public DbSet<StoppingReason> StoppingReasons { get; set; }
        public DbSet<KeyPopulation> KeyPopulations { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<PainScale> PainScales { get; set; }
        public DbSet<Disability> Disabilities { get; set; }
        public DbSet<ARTDrugClass> ARTDrugClasses { get; set; }
        public DbSet<ARTDrug> ARTDrugs { get; set; }
        public DbSet<TakenARTDrug> TakenARTDrugs { get; set; }
        public DbSet<TPTDrug> TPTDrugs { get; set; }
        public DbSet<DrugDosageUnit> DrugDosageUnites { get; set; }
        public DbSet<DrugFormulation> DrugFormulations { get; set; }
        public DbSet<DrugRegimen> DrugRegimens { get; set; }
        public DbSet<SpecialDrug> SpecialDrugs { get; set; }
        public DbSet<TBDrug> TBDrugs { get; set; }
        public DbSet<TBIdentificationMethod> TBIdentificationMethods { get; set; }
        public DbSet<ReasonOfReferral> ReasonOfReferrals { get; set; }
        public DbSet<ModeOfDelivery> ModeOfDeliveries { get; set; }
        public DbSet<NeonatalBirthOutcome> NeonatalBirthOutcomes { get; set; }
        public DbSet<CauseOfStillbirth> CauseOfStillbirths { get; set; }
        public DbSet<Breech> Breeches { get; set; }
        public DbSet<PresentingPart> PresentingParts { get; set; }
        public DbSet<CauseOfNeonatalDeath> CauseOfNeonatalDeaths { get; set; }
        public DbSet<PriorSensitization> PriorSensitizations { get; set; }
        public DbSet<CircumcisionReason> CircumcisionReasons { get; set; }
        public DbSet<WHOClinicalStage> WHOClinicalStages { get; set; }
        public DbSet<WHOStagesCondition> WHOStagesConditions { get; set; }
        public DbSet<VMMCCampaign> VMMCCampaigns { get; set; }
        public DbSet<ComplicationType> ComplicationTypes { get; set; }
        public DbSet<GynConfirmation> GynConfirmations { get; set; }
        public DbSet<CompositeTest> CompositeTests { get; set; }
        public DbSet<DrugClass> DrugClasses { get; set; }
        public DbSet<DrugSubclass> DrugSubclasses { get; set; }
        public DbSet<DrugUtility> DrugUtilities { get; set; }
        public DbSet<DrugRoute> DrugRoutes { get; set; }
        public DbSet<GenericDrug> GenericDrugs { get; set; }
        public DbSet<PreferredFeeding> PreferredFeedings { get; set; }
        public DbSet<TestType> TestTypes { get; set; }
        public DbSet<TestSubtype> TestSubTypes { get; set; }
        public DbSet<TBFinding> TBFindings { get; set; }
        public DbSet<TBSuspectingReason> TBSuspectingReasons { get; set; }
        public DbSet<ResultOption> ResultOptions { get; set; }
        public DbSet<PastMedicalCondition> PastMedicalConditions { get; set; }
        public DbSet<STIRisk> STIRisks { get; set; }
        public DbSet<FamilyPlanningClass> FamilyPlaningClasses { get; set; }
        public DbSet<FamilyPlanningSubclass> FamilyPlanningSubclasses { get; set; }
        public DbSet<FrequencyInterval> FrequencyIntervals { get; set; }
        public DbSet<Dispense> Dispenses { get; set; }
        public DbSet<MedicineManufacturer> MedicineManufacturers { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<FacilityQueue> FacilityQueues { get; set; }
        public DbSet<ArmedForceService> ArmedForceServices { get; set; }
        public DbSet<DFZPatientType> DFZPatientTypes { get; set; }
        public DbSet<DFZRank> DFZRanks { get; set; }
        public DbSet<ThermoAblationTreatmentMethod> ThermoAblationTreatmentMethods { get; set; }
        public DbSet<LeepsTreatmentMethod> LeepsTreatmentMethods { get; set; }
        public DbSet<InterCourseStatus> InterCourseStatuses { get; set; }
        #endregion

        #region Transactional Entities
        public DbSet<UserAccount> UserAccounts { get; set; }
        public DbSet<FacilityAccess> FacilityAccesses { get; set; }
        public DbSet<ModuleAccess> ModuleAccesses { get; set; }
        public DbSet<RecoveryRequest> RecoveryRequests { get; set; }
        public DbSet<LoginHistory> LoginHistories { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Vital> Vitals { get; set; }
        public DbSet<HTS> HTS { get; set; }
        public DbSet<RiskAssessment> RiskAssessments { get; set; }
        public DbSet<BirthRecord> BirthRecords { get; set; }
        public DbSet<DeathCause> DeathCauses { get; set; }
        public DbSet<Covid> Covids { get; set; }
        public DbSet<CovidSymptomScreening> CovidSymptomScreenings { get; set; }
        public DbSet<CovidComorbidity> CovidComorbidities { get; set; }
        public DbSet<ExposureRisk> ExposureRisks { get; set; }
        public DbSet<ImmunizationRecord> ImmunizationRecords { get; set; }
        public DbSet<AdverseEvent> AdverseEvents { get; set; }
        public DbSet<Covax> Covaxes { get; set; }
        public DbSet<CovaxRecord> CovaxRecords { get; set; }
        public DbSet<ChiefComplaint> ChiefComplaints { get; set; }
        public DbSet<IdentifiedConstitutionalSymptom> IdentifiedConstitutionalSymptoms { get; set; }
        public DbSet<IdentifiedTBSymptom> IdentifiedTBSymptoms { get; set; }
        public DbSet<SystemReview> SystemReviews { get; set; }
        public DbSet<MedicalHistory> MedicalHistories { get; set; }
        public DbSet<Condition> Conditions { get; set; }
        public DbSet<IdentifiedAllergy> IdentifiedAllergies { get; set; }
        public DbSet<ContraceptiveHistory> ContraceptiveHistories { get; set; }
        public DbSet<GynObsHistory> GynObsHistories { get; set; }
        public DbSet<BirthHistory> BirthHistories { get; set; }
        public DbSet<FeedingHistory> FeedingHistories { get; set; }
        public DbSet<ChildsDevelopmentHistory> ChildsDevelopmentHistories { get; set; }
        public DbSet<Assessment> Assessments { get; set; }
        public DbSet<SystemExamination> SystemExaminations { get; set; }
        public DbSet<GlasgowComaScale> GlasgowComaScales { get; set; }
        public DbSet<Diagnosis> Diagnoses { get; set; }
        public DbSet<Surgery> Surgeries { get; set; }
        public DbSet<TreatmentPlan> TreatmentPlans { get; set; }
        public DbSet<Exposure> Exposures { get; set; }
        public DbSet<DrugAdherence> DrugAdherences { get; set; }
        public DbSet<HIVPreventionHistory> HIVPreventionHistories { get; set; }
        public DbSet<RiskStatus> RiskStatuses { get; set; }
        public DbSet<Plan> Plans { get; set; }
        public DbSet<KeyPopulationDemographic> KeyPopulationDemographics { get; set; }
        public DbSet<HIVRiskScreening> HIVRiskScreenings { get; set; }
        public DbSet<Nutrition> Nutritions { get; set; }
        public DbSet<CounsellingService> CounsellingServices { get; set; }
        public DbSet<NursingPlan> NursingPlans { get; set; }
        public DbSet<TurningChart> TurningCharts { get; set; }
        public DbSet<Fluid> Fluids { get; set; }
        public DbSet<FluidIntake> FluidIntakes { get; set; }
        public DbSet<FluidOutput> FluidsOutputs { get; set; }
        public DbSet<PainRecord> PainRecords { get; set; }
        public DbSet<Encounter> Encounters { get; set; }
        public DbSet<Interaction> Interactions { get; set; }
        public DbSet<ARTService> ARTServices { get; set; }
        public DbSet<AttachedFacility> AttachedFacilities { get; set; }
        public DbSet<FamilyMember> FamilyMembers { get; set; }
        public DbSet<NextOfKin> NextOfKins { get; set; }
        public DbSet<PatientStatus> PatientStatuses { get; set; }
        public DbSet<DSDAssessment> DSDAssesments { get; set; }
        public DbSet<VisitPurpose> VisitPurposes { get; set; }
        public DbSet<ARTResponse> ARTResponses { get; set; }
        public DbSet<PriorARTExposure> PriorARTExposures { get; set; }
        public DbSet<TPTHistory> TPTHistories { get; set; }
        public DbSet<TakenTPTDrug> TakenTPTDrugs { get; set; }
        public DbSet<ARTDrugAdherence> ARTDrugAdherences { get; set; }
        public DbSet<TBHistory> TBHistories { get; set; }
        public DbSet<TakenTBDrug> TakenTBDrugs { get; set; }
        public DbSet<UsedTBIdentificationMethod> UsedTBIdentificationMethods { get; set; }
        public DbSet<ARTTreatmentPlan> ARTTreatmentPlans { get; set; }
        public DbSet<ClientsDisability> ClientsDisabilities { get; set; }
        public DbSet<PMTCT> PMTCTs { get; set; }
        public DbSet<ReferralModule> ReferralModules { get; set; }
        public DbSet<IdentifiedReferralReason> IdentifiedReferralReasons { get; set; }
        public DbSet<MotherDeliverySummary> MotherDeliverySummaries { get; set; }
        public DbSet<IdentifiedDeliveryIntervention> IdentifiedDeliveryInterventions { get; set; }
        public DbSet<IdentifiedCurrentDeliveryComplication> IdentifiedCurrentDeliveryComplications { get; set; }
        public DbSet<ThirdStageDelivery> ThirdStageDeliveries { get; set; }
        public DbSet<PPHTreatment> PPHTreatments { get; set; }
        public DbSet<IdentifiedPPHTreatment> IdentifiedPPHTreatments { get; set; }
        public DbSet<MedicalTreatment> MedicalTreatments { get; set; }
        public DbSet<UterusCondition> UterusConditions { get; set; }
        public DbSet<PlacentaRemoval> PlacentaRemovals { get; set; }
        public DbSet<IdentifiedPlacentaRemoval> IdentifiedPlacentaRemovals { get; set; }
        public DbSet<PerineumIntact> PeriuneumIntacts { get; set; }
        public DbSet<IdentifiedPerineumIntact> IdentifiedPeriuneumIntacts { get; set; }
        public DbSet<NewBornDetail> NewBornDetails { get; set; }
        public DbSet<ApgarScore> ApgarScores { get; set; }
        public DbSet<NeonatalDeath> NeonatalDeaths { get; set; }
        public DbSet<NeonatalAbnormality> NeonatalAbnormalities { get; set; }
        public DbSet<NeonatalInjury> NeonatalInjuries { get; set; }
        public DbSet<FeedingMethod> FeedingMethods { get; set; }
        public DbSet<DischargeMetric> DischargeMetrics { get; set; }
        public DbSet<Partograph> Partographs { get; set; }
        public DbSet<PartographDetail> PartographDetails { get; set; }
        public DbSet<BirthDetail> BirthDetails { get; set; }
        public DbSet<Volume> Volumes { get; set; }
        public DbSet<Acetone> Acetones { get; set; }
        public DbSet<Protein> Proteins { get; set; }
        public DbSet<Temperature> Temperatures { get; set; }
        public DbSet<Pulse> Pulses { get; set; }
        public DbSet<BloodPressure> BloodPressures { get; set; }
        public DbSet<Medicine> Medicines { get; set; }
        public DbSet<Drop> Drops { get; set; }
        public DbSet<Oxytocin> Oxytocins { get; set; }
        public DbSet<Contraction> Contractions { get; set; }
        public DbSet<DescentOfHead> DescentOfHeads { get; set; }
        public DbSet<Cervix> Cervixes { get; set; }
        public DbSet<Moulding> Mouldings { get; set; }
        public DbSet<Liquor> Liquors { get; set; }
        public DbSet<FetalHeartRate> FetalHeartRates { get; set; }
        public DbSet<ServiceQueue> ServiceQueues { get; set; }
        public DbSet<BloodTransfusionHistory> BloodTransfusionHistories { get; set; }
        public DbSet<Caregiver> Caregivers { get; set; }
        public DbSet<ChildDetail> ChildDetails { get; set; }
        public DbSet<IdentifiedPriorSensitization> IdentifiedPriorSensitizations { get; set; }
        public DbSet<AnestheticPlan> AnestheticPlans { get; set; }
        public DbSet<VisitDetail> VisitDetails { get; set; }
        public DbSet<VaginalPosition> VaginalPositions { get; set; }
        public DbSet<WHOCondition> WHOConditions { get; set; }
        public DbSet<VMMCService> VMMCServices { get; set; }
        public DbSet<ANCService> ANCServices { get; set; }
        public DbSet<ANCScreening> ANCScreenings { get; set; }
        public DbSet<Complication> Complications { get; set; }
        public DbSet<IdentifiedComplication> IdentifiedComplications { get; set; }
        public DbSet<PregnancyBooking> PregnancyBookings { get; set; }
        public DbSet<IdentifiedPregnancyConfirmation> IdentifiedPregnencyConfirmations { get; set; }
        public DbSet<GuidedExamination> GuidedExaminations { get; set; }
        public DbSet<MotherDetail> MotherDetails { get; set; }
        public DbSet<QuickExamination> QuickExaminations { get; set; }
        public DbSet<ScreeningAndPrevention> ScreeningAndPreventions { get; set; }
        public DbSet<ObstetricExamination> ObstericExaminations { get; set; }
        public DbSet<DrugPickUpSchedule> DrugPickUpSchedules { get; set; }
        public DbSet<TestItem> TestItems { get; set; }
        public DbSet<TBService> TBServices { get; set; }
        public DbSet<IdentifiedTBFinding> IdentifiedTBFindings { get; set; }
        public DbSet<InsertionAndRemovalProcedure> InsertionAndRemovalProcedures { get; set; }
        public DbSet<Dot> Dots { get; set; }
        public DbSet<DotCalendar> DotCalenders { get; set; }
        public DbSet<IdentifiedReason> IdentifiedReasons { get; set; }
        public DbSet<PelvicAndVaginalExamination> PelvicAndVaginalExaminations { get; set; }
        public DbSet<Investigation> Investigations { get; set; }
        public DbSet<MeasuringUnit> MeasuringUnits { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<Prescription> Prescriptions { get; set; }
        public DbSet<PastAntenatalVisit> PastAntenatalVisits { get; set; }
        public DbSet<IdentifiedCordStump> IdentifiedCordStumps { get; set; }
        public DbSet<IdentifiedEyesAssessment> IdentifiedEyesAssessments { get; set; }
        public DbSet<IdentifiedPreferredFeeding> IdentifiedPreferredFeedings { get; set; }
        public DbSet<OptedCircumcisionReason> OptedCircumcisionReasons { get; set; }
        public DbSet<OptedVMMCCampaign> OptedVMMCCampaigns { get; set; }
        public DbSet<MedicalCondition> MedicalConditions { get; set; }
        public DbSet<FamilyPlan> FamilyPlans { get; set; }
        public DbSet<FamilyPlanRegister> FamilyPlanRegisters { get; set; }
        public DbSet<GeneralDrugDefinition> GeneralDrugDefinitions { get; set; }
        public DbSet<SystemRelevance> SystemsRelevances { get; set; }
        public DbSet<Medication> Medications { get; set; }
        public DbSet<MedicineBrand> MedicineBrands { get; set; }
        public DbSet<DispensedItem> DispensedItems { get; set; }

        //public DbSet<CareProLog> CareProLogs { get; set; }
        public DbSet<DFZClient> DFZClients { get; set; }
        public DbSet<DFZDependent> DFZDependents { get; set; }
        public DbSet<PreScreeningVisit> PreScreeningVisits { get; set; }
        public DbSet<ThermoAblation> ThermoAblations { get; set; }
        public DbSet<Leeps> Leeps { get; set; }
        public DbSet<CaCXPlan> CaCXPlans { get; set; }
        public DbSet<Screening> Screenings { get; set; } 
    }
    #endregion
}