using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Utilities.Constants;

/*
 * Created by   : Tomas
 * Date created : 15.03.2023
 * Modified by  : Bella
 * Last modified: 30.03.2023
 * Reviewed by  :
 * Date reviewed:
 */
namespace Domain.Entities
{
   /// <summary>
   /// ART Registers entity.
   /// </summary>
   public class ARTService : EncounterBaseModel
   {
      /// <summary>
      /// Primary Key of the table ARTRegisters.
      /// </summary>
      [Key, ForeignKey("Client")]
      public Guid Oid { get; set; }

      /// <summary>
      /// ART Number of the ART Service.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [StringLength(60)]
      [Display(Name = "ART Number")]
      public string ARTNumber { get; set; }

      /// <summary>
      /// Is ART Number Auto Generated.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Is ART Number Auto Generated")]
      public bool IsARTNumberAutoGenerated { get; set; }

      /// <summary>
      /// Disclosure Councelling of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Disclosure Counselling")]
      public bool DisclosureCounselling { get; set; }

      /// <summary>
      /// CoupleCouncelling of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Couple Counselling")]
      public bool CoupleCounselling { get; set; }

      /// <summary>
      /// NotificationServices of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Index Testing and Partner Notification Services(IT & PNS)")]
      public bool NotificationServices { get; set; }

      /// <summary>
      /// InterpersonalViolenceScreened of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Screened for interpersonal violence")]
      public bool InterpersonalViolenceScreened { get; set; }

      /// <summary>
      /// Is ITPNS Offered ?
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Patient offered IT & PNS")]
      public bool IsITPNSOffered { get; set; }

      /// <summary>
      /// Is ITPNS Accepted ?
      /// </summary>
      [Display(Name = "Patient accepted IT & PNS")]
      public bool IsITPNSAccepted { get; set; }

      /// <summary>
      /// NumberOfBiologicalContacts of the table ARTRegisters.
      /// </summary>
      [Column(TypeName = "SMALLINT")]
      [Display(Name = "Biological contacts")]
      public int? NumberOfBiologicalContacts { get; set; }

      /// <summary>
      /// NumberOfSexualContacts of the table ARTRegisters.
      /// </summary>
      [Column(TypeName = "SMALLINT")]
      [Display(Name = "Sexual contacts")]
      public int? NumberOfSexualContacts { get; set; }

      /// <summary>
      /// NumberOfOtherContacts of the table ARTRegisters.
      /// </summary>
      [Column(TypeName = "SMALLINT")]
      [Display(Name = "Other contacts")]
      public int? NumberOfOtherContacts { get; set; }

      /// <summary>
      /// ConsentForFollowupPrograms of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Does patient consent for follow up programs")]
      public bool ConsentForFollowUpPrograms { get; set; }

      /// <summary>
      /// CanReceiveCalls of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Does patient receive calls ? ")]
      public bool CanReceiveCalls { get; set; }

      /// <summary>
      /// CanReceiveSMS of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Does patient receive sms ? ")]
      public bool CanReceiveSMS { get; set; }

      /// <summary>
      /// CanPatientBeVisitedHome of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Does patient be visited at home ? ")]
      public bool CanPatientBeVisitedAtHome { get; set; }

      /// <summary>
      /// CanPatientBeVisitedWork of the table ARTRegisters.
      /// </summary>
      [Required(ErrorMessage = MessageConstants.RequiredFieldError)]
      [Display(Name = "Does patient be visited at work ? ")]
      public bool CanPatientBeVisitedAtWork { get; set; }

      /// <summary>
      /// Is Enrolled in Support Group.
      /// </summary>
      [Display(Name = "Is Enrolled in Support Group?")]
      public bool IsEnrolledInSupportGroup { get; set; }

      /// <summary>
      /// Does Client wants to be enrolled in Support Group?
      /// </summary>
      [Display(Name = "Does Client want to be enrolled in Support Group? ")]
      public bool DoesClientWantToBeEnrolledInSupportGroup { get; set; }

      [Display(Name = "Does Child Know Status?")]
      public bool DoesChildKnowStatus { get; set; }

      /// <summary>
      /// Navigation property.
      /// </summary>
      [JsonIgnore]
      public virtual Client Client { get; set; }

      // <summary>
      /// Patient Statuses of the ART.
      // </summary>
      [JsonIgnore]
      public virtual IEnumerable<PatientStatus> PatientStatuses { get; set; }

      // <summary>
      /// Temporary ART number in client side.
      // </summary>
      [NotMapped]
      public string ARTTempNumber { get; set; }
   }
}