using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class InitialCreateARTServices : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ARTServices",
                columns: table => new
                {
                    Oid = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ARTNumber = table.Column<string>(type: "nvarchar(60)", maxLength: 60, nullable: false),
                    IsARTNumberAutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    DisclosureCounselling = table.Column<bool>(type: "bit", nullable: false),
                    CoupleCounselling = table.Column<bool>(type: "bit", nullable: false),
                    NotificationServices = table.Column<bool>(type: "bit", nullable: false),
                    InterpersonalViolenceScreened = table.Column<bool>(type: "bit", nullable: false),
                    IsITPNSOffered = table.Column<bool>(type: "bit", nullable: false),
                    IsITPNSAccepted = table.Column<bool>(type: "bit", nullable: false),
                    NumberOfBiologicalContacts = table.Column<short>(type: "SMALLINT", nullable: false),
                    NumberOfSexualContacts = table.Column<short>(type: "SMALLINT", nullable: false),
                    NumberOfOtherContacts = table.Column<short>(type: "SMALLINT", nullable: false),
                    ConsentForFollowUpPrograms = table.Column<bool>(type: "bit", nullable: false),
                    CanReceiveCalls = table.Column<bool>(type: "bit", nullable: false),
                    CanReceiveSMS = table.Column<bool>(type: "bit", nullable: false),
                    CanPatientBeVisitedAtHome = table.Column<bool>(type: "bit", nullable: false),
                    CanPatientBeVisitedAtWork = table.Column<bool>(type: "bit", nullable: false),
                    IsEnrolledInSupportGroup = table.Column<bool>(type: "bit", nullable: false),
                    DoesClientWantToBeEnrolledInSupportGroup = table.Column<bool>(type: "bit", nullable: false),
                    DoesChildKnowStatus = table.Column<bool>(type: "bit", nullable: false),
                    EncounterId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    EncounterType = table.Column<byte>(type: "tinyint", nullable: false),
                    CreatedIn = table.Column<int>(type: "int", nullable: true),
                    DateCreated = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ModifiedIn = table.Column<int>(type: "int", nullable: true),
                    DateModified = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ModifiedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: true),
                    IsSynced = table.Column<bool>(type: "bit", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ARTServices", x => x.Oid);
                    table.ForeignKey(
                        name: "FK_ARTServices_Clients_Oid",
                        column: x => x.Oid,
                        principalTable: "Clients",
                        principalColumn: "Oid",
                        onDelete: ReferentialAction.Cascade);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ARTServices");
        }
    }
}
